name: Build Linux kernel (LLVM)

on:
  push:
    tags:
      - 'v*.*'   # e.g. v6.6
  workflow_dispatch:
    inputs:
      version:
        description: 'Linux version/tag to build (default: v6.6)'
        required: false
        default: 'v6.6'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, riscv]
    steps:
      - name: Checkout kernel
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: ${{ github.event.inputs.version || 'v6.6' }}

      - name: Download LLVM toolchain
        run: |
          wget https://github.com/OS-Jerry/My-llvm-clang-toolchain/releases/download/llvmorg-21.1.0/clang-toolchain-llvmorg-21.1.0.tar.gz
          mkdir -p llvm-toolchain
          tar -xzf clang-toolchain-llvmorg-21.1.0.tar.gz -C llvm-toolchain --strip-components=1
          echo "$GITHUB_WORKSPACE/llvm-toolchain/bin:$PATH" >> $GITHUB_PATH

      - name: Verify LLVM tools
        run: |
          which clang
          which ld.lld
          clang --version
          ld.lld --version

      - name: Configure Linux Kernel for ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            make ARCH=arm64 LLVM=1 LLVM_IAS=1 defconfig
          else
            make ARCH=riscv LLVM=1 LLVM_IAS=1 defconfig
          fi

      - name: Build Linux Kernel for ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            make -j$(nproc) ARCH=arm64 LLVM=1 LLVM_IAS=1
          else
            make -j$(nproc) ARCH=riscv LLVM=1 LLVM_IAS=1
          fi

      - name: Package build output
        run: |
          mkdir -p artifacts
          tar -czf artifacts/linux-${{ matrix.arch }}-${{ github.event.inputs.version || 'v6.6' }}.tar.gz .

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-${{ matrix.arch }}-${{ github.event.inputs.version || 'v6.6' }}
          path: artifacts/linux-${{ matrix.arch }}-${{ github.event.inputs.version || 'v6.6' }}.tar.gz

