name: Build Linux Kernel with GCC

on:
  push:
    tags:
      - 'v*.*'   # e.g. v6.6
  workflow_dispatch:
    inputs:
      version:
        description: 'Linux kernel version/tag to build (default: v6.6)'
        required: false
        default: 'v6.6'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - arm64
          - riscv
      fail-fast: false

    steps:
      - name: Checkout Linux Kernel repository
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: ${{ github.event.inputs.version || 'v6.6' }}

      - name: Setup Clang Toolchain
        run: |
          mkdir -p /opt/llvm
          curl -L https://github.com/OS-Jerry/My-llvm-clang-toolchain/releases/download/llvmorg-21.1.0/clang-toolchain-llvmorg-21.1.0.tar.gz \
            | tar -xz -C /opt/llvm
          echo "/opt/llvm/clang-toolchain-llvmorg-21.1.0/bin" >> $GITHUB_PATH

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses-dev \
            bison \
            flex \
            libssl-dev \
            bc \
            wget \
            gcc-aarch64-linux-gnu \
            gcc-riscv64-linux-gnu

      - name: Configure Linux kernel for ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -C $GITHUB_WORKSPACE/../arm64 defconfig
          elif [ "${{ matrix.arch }}" == "riscv" ]; then
            make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- -C $GITHUB_WORKSPACE/../riscv defconfig
          fi

      - name: Build Linux kernel for ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) all
          elif [ "${{ matrix.arch }}" == "riscv" ]; then
            make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- -j$(nproc) all
          fi

      - name: Archive kernel build output
        if: success()
        run: |
          mkdir -p artifacts
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            cp arch/arm64/boot/Image artifacts/
          elif [ "${{ matrix.arch }}" == "riscv" ]; then
            cp arch/riscv/boot/Image artifacts/
          fi
          tar -czf artifacts/linux-${{ matrix.arch }}-${{ github.event.inputs.version || 'v6.6' }}.tar.gz -C artifacts Image

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-${{ matrix.arch }}-${{ github.event.inputs.version || 'v6.6' }}
          path: artifacts/linux-${{ matrix.arch }}-${{ github.event.inputs.version || 'v6.6' }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_artifacts
  
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || 'v6.6' }}
          files: release_artifacts/**/*
